name: fpsgen
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch=1.13.0
  - torchvision=0.14.0
  - pytorch-cuda=11.7
  - pip=23.3
  - ninja
  - pip:
      - -r requirements.txt
